### ISSUE TITLE
Covid Registration

### ISSUE THREAD

**Issue by Tararala** [lampyjon/bullets-with-shop#22]
- Email everyone who has registered and ask them to check their contact details, update in necessary. Also, confirm they agree to the COVID guidance.
- Make a list/page for the COVID guidance
- Add the COVID agreement on the main registration flow
- Make it possible to search a list of people who have agreed to the COVID guidance

**Comment by lampyjon** [comment]
Points 2 and 3 done, point 1 partially; point 4 still to do.
